In [2]:
import numpy as np
import pandas as pd
import re

## 각 데이터 불러오기 및 생성

### 가격정보 데이터

In [5]:
# 전통시장 품목별 가격정보 데이터
price_2013_2017 = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/huge/생필품 농수축산물 가격 정보(2013년_2017년).csv', encoding='CP949', engine='python')
price_2018 = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/huge/생필품 농수축산물 가격 정보(2018년).csv', encoding='CP949', engine='python')
price_2019 = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/huge/생필품 농수축산물 가격 정보(2019년).csv', encoding='CP949', engine='python')
price_2020 = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/huge/생필품 농수축산물 가격 정보(2020년).csv', encoding='CP949', engine='python')

In [24]:
# price 테이블을 하나로 통합
price_all = pd.concat([price_2020, price_2019, price_2018, price_2013_2017])
price_all

,일련번호,시장/마트 번호,시장/마트 이름,품목 번호,품목 이름,실판매규격,가격(원),년도-월,비고,시장유형 구분(시장/마트) 코드,시장유형 구분(시장/마트) 이름,자치구 코드,자치구 이름,점검일자
0,1621162,1,통인시장,309,양파(1.5kg망),1kg,2000,2020-12,"국내산,무안",1,전통시장,110000,종로구,2020-12-21
1,1628949,228,방배종합시장,277,호박,1개268g,1500,2020-12,국내산/인큐베이터,1,전통시장,650000,서초구,2020-12-21
2,1626799,51,NC백화점 불광점,18,닭고기,1마리(1kg),8990,2020-12,올품 토종,2,대형마트,380000,은평구,2020-12-21
3,1630920,223,홈플러스 목동점,278,쇠고기,600g,35982,2020-12,국내산(음성)농협,2,대형마트,470000,양천구,2020-12-21
4,1622882,1,통인시장,309,양파(1.5kg망),1kg,2000,2020-12,"국내산,무안",1,전통시장,110000,종로구,2020-12-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97068,406492,146,방이시장,171,달걀(특란),10개,2150,2013-01,신선특란,1,전통시장,710000,송파구,2013-01-31
97069,406493,146,방이시장,259,"조기(냉동,국산)",1마리(20cm),1780,2013-01,2마리 3560원,1,전통시장,710000,송파구,2013-01-31
97070,406494,146,방이시장,152,"명태(러시아,냉동)",1마리(45cm),5000,2013-01,행사,1,전통시장,710000,송파구,2013-01-31
97071,406495,146,방이시장,256,"오징어(냉동,국산)",1마리(25cm),3000,2013-01,해동,1,전통시장,710000,송파구,2013-01-31
97072,406496,146,방이시장,266,"고등어(생물,국산)",1마리(30cm),5000,2013-01,대,1,전통시장,710000,송파구,2013-01-31

In [450]:
# 전통시장에 해당하는 row만 추출
is_price_trd = price_all['시장유형 구분(시장/마트) 이름'] == '전통시장'
price_trd = price_all[is_price_trd]
price_trd

,일련번호,시장/마트 번호,시장/마트 이름,품목 번호,품목 이름,실판매규격,가격(원),년도-월,비고,시장유형 구분(시장/마트) 코드,시장유형 구분(시장/마트) 이름,자치구 코드,자치구 이름,점검일자
0,1621162,1,통인시장,309,양파(1.5kg망),1kg,2000,2020-12,"국내산,무안",1,전통시장,110000,종로구,2020-12-21
1,1628949,228,방배종합시장,277,호박,1개268g,1500,2020-12,국내산/인큐베이터,1,전통시장,650000,서초구,2020-12-21
4,1622882,1,통인시장,309,양파(1.5kg망),1kg,2000,2020-12,"국내산,무안",1,전통시장,110000,종로구,2020-12-21
6,1622883,1,통인시장,310,상추(100g),400g,3000,2020-12,"국내산,적상추",1,전통시장,110000,종로구,2020-12-21
8,1622885,1,통인시장,119,호박(인큐베이터),1개,1000,2020-12,"국내산,",1,전통시장,110000,종로구,2020-12-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97068,406492,146,방이시장,171,달걀(특란),10개,2150,2013-01,신선특란,1,전통시장,710000,송파구,2013-01-31
97069,406493,146,방이시장,259,"조기(냉동,국산)",1마리(20cm),1780,2013-01,2마리 3560원,1,전통시장,710000,송파구,2013-01-31
97070,406494,146,방이시장,152,"명태(러시아,냉동)",1마리(45cm),5000,2013-01,행사,1,전통시장,710000,송파구,2013-01-31
97071,406495,146,방이시장,256,"오징어(냉동,국산)",1마리(25cm),3000,2013-01,해동,1,전통시장,710000,송파구,2013-01-31
97072,406496,146,방이시장,266,"고등어(생물,국산)",1마리(30cm),5000,2013-01,대,1,전통시장,710000,송파구,2013-01-31

In [451]:
# 분석에 필요한 열만 추출 및 생성
df_price = price_trd[['년도-월','시장/마트 이름','품목 이름', '실판매규격', '가격(원)', '자치구 이름']]
df_price.rename(columns = {'시장/마트 이름':'시장이름', '품목 이름':'품목이름', '자치구 이름':'자치구명'}, inplace = True)
df_price

C:\Users\123gu\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

          년도-월    시장이름        품목이름      실판매규격  가격(원) 자치구명
0      2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
1      2020-12  방배종합시장          호박     1개268g   1500  서초구
4      2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
6      2020-12    통인시장    상추(100g)       400g   3000  종로구
8      2020-12    통인시장   호박(인큐베이터)         1개   1000  종로구
...        ...     ...         ...        ...    ...  ...
97068  2013-01    방이시장      달걀(특란)        10개   2150  송파구
97069  2013-01    방이시장   조기(냉동,국산)  1마리(20cm)   1780  송파구
97070  2013-01    방이시장  명태(러시아,냉동)  1마리(45cm)   5000  송파구
97071  2013-01    방이시장  오징어(냉동,국산)  1마리(25cm)   3000  송파구
97072  2013-01    방이시장  고등어(생물,국산)  1마리(30cm)   5000  송파구

[171043 rows x 6 columns]

In [452]:
# index 재설정
df_price = df_price.reset_index().drop(['index'], axis=1)
df_price

           년도-월    시장이름        품목이름      실판매규격  가격(원) 자치구명
0       2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
1       2020-12  방배종합시장          호박     1개268g   1500  서초구
2       2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
3       2020-12    통인시장    상추(100g)       400g   3000  종로구
4       2020-12    통인시장   호박(인큐베이터)         1개   1000  종로구
...         ...     ...         ...        ...    ...  ...
171038  2013-01    방이시장      달걀(특란)        10개   2150  송파구
171039  2013-01    방이시장   조기(냉동,국산)  1마리(20cm)   1780  송파구
171040  2013-01    방이시장  명태(러시아,냉동)  1마리(45cm)   5000  송파구
171041  2013-01    방이시장  오징어(냉동,국산)  1마리(25cm)   3000  송파구
171042  2013-01    방이시장  고등어(생물,국산)  1마리(30cm)   5000  송파구

[171043 rows x 6 columns]

In [175]:
# 데이터 타입 확인
print(' 년도-월 : ', type(df_price['년도-월'][0]),'\n', '가격(원) : ', type(df_price['가격(원)'][0]))

 년도-월 :  <class 'str'>
 가격(원) :  <class 'numpy.int64'>

In [191]:
# 유동인구 데이터와 호환을 위한 년도, 분기 column 생성
year = []
quarter = []
for i in range(len(df_price['년도-월'])):
    if df_price['년도-월'][i][5:7] in ['01','02','03'] :
        quarter.append('1')
    if df_price['년도-월'][i][5:7] in ['04','05','06'] :
        quarter.append('2')
    if df_price['년도-월'][i][5:7] in ['07','08','09'] :
        quarter.append('3')
    if df_price['년도-월'][i][5:7] in ['10','11','12'] :
        quarter.append('4') 
    year.append(df_price['년도-월'][i][0:4])

In [203]:
# 유동인구 테이블의 년도, 분기 모두 int이므로 str -> int로 변환
for i in range(len(year)):
    year[i] = int(year[i])
    
for i in range(len(quarter)):
    quarter[i] = int(quarter[i])  
    
print(type(year[0]),type(year[len(year)-1]),type(quarter[0]),type(quarter[len(quarter)-1]))

<class 'int'> <class 'int'> <class 'int'> <class 'int'>

In [453]:
# int로 생성한 년도, 분기 column 삽입
df_price.insert(0, '년도', year, True)
df_price.insert(1, '분기', quarter, True)
df_price

          년도  분기     년도-월    시장이름        품목이름      실판매규격  가격(원) 자치구명
0       2020   4  2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
1       2020   4  2020-12  방배종합시장          호박     1개268g   1500  서초구
2       2020   4  2020-12    통인시장  양파(1.5kg망)        1kg   2000  종로구
3       2020   4  2020-12    통인시장    상추(100g)       400g   3000  종로구
4       2020   4  2020-12    통인시장   호박(인큐베이터)         1개   1000  종로구
...      ...  ..      ...     ...         ...        ...    ...  ...
171038  2013   1  2013-01    방이시장      달걀(특란)        10개   2150  송파구
171039  2013   1  2013-01    방이시장   조기(냉동,국산)  1마리(20cm)   1780  송파구
171040  2013   1  2013-01    방이시장  명태(러시아,냉동)  1마리(45cm)   5000  송파구
171041  2013   1  2013-01    방이시장  오징어(냉동,국산)  1마리(25cm)   3000  송파구
171042  2013   1  2013-01    방이시장  고등어(생물,국산)  1마리(30cm)   5000  송파구

[171043 rows x 8 columns]

### 주소 데이터

In [55]:
# 전통시장 주소. 위도 경도 데이터
address = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/서울 전통시장 주소.csv', encoding='CP949', engine='python')
address

     자치구 코드  자치구명           전통시장명          주소명         위도          경도
0        22   은평구            갈현시장   갈현동 424-16  37.623587  126.917385
1        12   동작구            강남시장      상도동 488  37.518749  127.020640
2         1   강남구            강남시장    신사동510-11  37.496746  126.953488
3         1   강남구       강남역 지하도상가     역삼동821-1  37.498595  127.028026
4        15   서초구  강남터미널지하도상점가1구역  서초구 반포동 163  37.500478  126.986060
..      ...   ...             ...          ...        ...         ...
325       4   강서구          화곡중앙시장   화곡동 370-76  37.535339  126.839467
326       6   광진구        화양제일골목시장    화양동 34-72  37.543482  127.069252
327      11  동대문구            회기시장    회기동 57-22  37.590936  127.054940
328      24    중구         회현지하도상가     중구 회현동2가  37.557286  126.979322
329      21   용산구            후암시장      후암동 103  37.550008  126.976553

[330 rows x 6 columns]

In [353]:
df_address = address[['전통시장명', '위도', '경도']]
df_address.rename(columns = {'전통시장명':'시장이름'}, inplace = True)
df_address

C:\Users\123gu\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

               시장이름         위도          경도
0              갈현시장  37.623587  126.917385
1              강남시장  37.518749  127.020640
2              강남시장  37.496746  126.953488
3         강남역 지하도상가  37.498595  127.028026
4    강남터미널지하도상점가1구역  37.500478  126.986060
..              ...        ...         ...
325          화곡중앙시장  37.535339  126.839467
326        화양제일골목시장  37.543482  127.069252
327            회기시장  37.590936  127.054940
328         회현지하도상가  37.557286  126.979322
329            후암시장  37.550008  126.976553

[330 rows x 3 columns]

### 유동인구 데이터

In [43]:
# 전통시장 유동인구 데이터
customer = pd.read_csv('C:/Users/123gu/Desktop/data-visualization-8/datas/huge/서울 전통시장 유동인구(2014년_2020년 분기단위).csv', encoding='CP949', engine='python')
customer.head(2)

,기준 년코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,U,관광특구,1001496,강남 마이스 관광특구,90836,46313,44523,4351,...,142,140,123,39,48,99,124,123,104,35
1,2020,4,U,관광특구,1001495,잠실 관광특구,2956754,1445027,1511727,248574,...,5398,5785,7033,3989,7009,6350,5041,5460,6552,3868

In [208]:
# 전통시장에 해당하는 row만 추출
is_customer = customer[' 상권_구분_코드_명'] == '전통시장'
customer_trd = customer[is_customer]
customer_trd.head(2)

,기준 년코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
6,2020,4,R,전통시장,1001490,길동복조리시장,873376,396767,476609,144022,...,2478,2523,3412,2641,5460,4288,2493,2562,3545,2713
7,2020,4,R,전통시장,1001489,둔촌역전통시장,252938,122996,129942,36836,...,786,821,1165,657,1258,1082,780,830,1103,644

In [176]:
# 필요하지 않은 열 삭제, 열이름 재설정, 인덱스 재설정
df_customer = customer_trd.drop(['상권_구분_코드',' 상권_구분_코드_명', '상권_코드'], axis = 1)
df_customer.rename(columns = {'상권_코드_명':'시장이름', '기준 년코드':'년도', '기준_분기_코드':'분기'}, inplace = True)
df_customer = df_customer.reset_index().drop(['index'], axis=1)
df_customer

,년도,분기,시장이름,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,연령대_20_생활인구_수,연령대_30_생활인구_수,연령대_40_생활인구_수,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,길동복조리시장,873376,396767,476609,144022,94019,114971,136136,...,2478,2523,3412,2641,5460,4288,2493,2562,3545,2713
1,2020,4,둔촌역전통시장,252938,122996,129942,36836,31794,34053,40459,...,786,821,1165,657,1258,1082,780,830,1103,644
2,2020,4,성내골목시장,641789,288503,353286,100176,73678,99616,100460,...,1936,2199,3282,1741,3131,2678,1903,2250,3129,1694
3,2020,4,천호시장,91897,41183,50716,7332,16546,16344,14186,...,313,362,406,190,283,281,281,333,374,177
4,2020,4,동서울시장,66313,29932,36381,6265,9898,11419,9704,...,210,227,256,176,344,289,201,209,251,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6278,2014,1,충신시장,38363,24613,13750,236,5863,10314,10363,...,30,19,10,0,0,0,4,3,0,0
6279,2014,1,종로신진시장,190225,118296,71928,394,27801,48260,45866,...,283,226,91,3,0,1,12,23,14,2
6280,2014,1,동대문종합시장,496529,277937,218593,10582,98155,135325,112571,...,684,562,383,82,1,87,203,217,198,67
6281,2014,1,광장시장,238439,157317,81122,1059,22979,49399,59886,...,454,452,243,15,0,4,77,117,68,2
6282,2014,1,통인시장,85312,47128,38183,6375,12409,20240,21532,...,96,87,67,0,0,14,38,17,19,0

In [177]:
# 데이터 타입 확인
print(' 년도 : ', type(df_customer['년도'][0]), '\n', '분기 : ',type(df_customer['분기'][0]), '\n', '총_생활인구_수 : ',type(df_customer['총_생활인구_수'][0]))

 년도 :  <class 'numpy.int64'>
 분기 :  <class 'numpy.int64'>
 총_생활인구_수 :  <class 'numpy.int64'>

## 모두 결합해 최종 df 생성

### 가격 테이블에 주소 테이블 병합

In [383]:
# 가격 테이블에 있는 전통시장 수 확인
print(len(df_price['시장이름'].unique()), df_price['시장이름'].unique())

53 ['통인시장' '방배종합시장' '방학동도깨비시장' '장위골목시장' '신창시장' '마포농수산물시장' '동원시장' '광장시장'
 '남성시장' '금남시장' '뚝도시장' '후암시장' '청량리종합시장' '남문시장' '남구로시장' '신영시장' '고척근린시장'
 '용문시장' '대림시장' '영등포전통시장' '망원시장' '영천시장' '인왕시장' '신원시장(신림1동)' '자양골목시장'
 '수유재래시장' '경동시장' '우림시장' '송화시장' '대림중앙시장' '목3동시장' '공릉동 도깨비시장' '돈암제일시장'
 '원당종합시장' '남대문시장' '청담삼익시장' '현대시장' '둔촌역전통시장' '서울중앙시장' '노룬산골목시장' '화곡본동시장'
 '방이시장' '대조시장' '도곡시장' '마천중앙시장' '관악신사시장(신림4동)' '암사종합시장' '상계중앙시장' '숭인시장'
 '방림시장' '구로시장' '공릉동도깨비시장' '영동시장']

In [384]:
# 주소 테이블에 있는 전통시장 수 확인
print(len(df_address['시장이름'].unique()), df_address['시장이름'].unique())

327 ['갈현시장' '강남시장' '강남역 지하도상가' '강남터미널지하도상점가1구역' '강남터미널지하도상점가2구역'
 '강남터미널지하도상점가3구역' '강북종합골목시장' '강북종합시장' '개봉중앙시장' '개봉프라자' '개포2동 중심상가'
 '경동광성상가' '경동시장' '경창시장' '고덕전통시장' '고속터미널 지하철역 상점가 ' '고척근린시장' '고척프라자' '공덕시장'
 '공릉동 도깨비시장' '공무원연금매장 상록스토아 개포점' '공항시장' '관악신사시장(신림4동)' '관악종합시장' '광성시장'
 '광장골목시장' '광장시장' '광희시장' '구로시장' '구의시장' '굽은다리골목시장' '금남시장' '금천교시장' '길동골목시장'
 '길음시장' '까치산시장' '깡통시장(제기상가번영회)' '낙성대 시장(봉천7동)' '낙원상가' '낙원지하시장(대일상가)'
 '남구로시장(구 구로자율시장)' '남대문로 지하상가' '남대문시장' '남문시장' '남부골목시장' '남부종합시장' '남부화곡시장'
 '남서울상가' '남평화시장' '노룬산골목시장' '노룬산시장' '녹번시장' '논현종합시장' '능동로골목시장' '답십리시장'
 '답십리현대시장' '대림골목시장' '대림시장' '대림중앙시장' '대명시장' '대명시장 및 주변상점가' '대신시장' '대원종합시장'
 '대조시장' '도림시장' '도선동상점가' '도화동 상점가' '돈암제일시장' '동남상가' '동대문문구완구종합시장' '동대문상가A동'
 '동대문상가B동' '동대문상가C동' '동대문종합시장' '동대문종합시장D동상가' '동대문지하쇼핑센터' '동문시장' '동부골목시장'
 '동부시장' '동부청과시장' '동북시장' '동서시장' '동서울시장' '동성타워프라자' '동소문 스카이상가' '동원골목시장'
 '동원시장' '동진시장' '동평화시장' '동화시장' '두암시장' '둔촌역전통시장' '등마루시장' '뚝도시장' '로데오거리상점가'
 '로타리상가' '마장축산물시장' '마천시장' '마천중앙시장' '마포농수산물시장' '마포시장' '만리시장' '망원동월드컵시장'
 '망원시장' '면곡골목시장' '면목골목시장' '면목시장' '명동 지하도상가' '명동역지하도쇼핑센터' '명일골목시장' '모래내시장'
 '목2동시장' '목3동시장' '목4동시장' '목동제일시장' '문정동 로데오거리 상점가' '미성동 도깨비시장' '박미시장'
 '밤나무골시장' '방산시장' '방산종합시장' '방신재래시장' '방이시장' '방천골목시장' '방학동도깨비시장' '백련시장'
 '번동북부골목시장' '번동북부시장' '번동시장' '보광시장' '보문골목시장' '본동인정시장' '봉일시장' '봉천신시장'
 '봉천제일종합시장' '봉천중앙시장' '봉천현대시장' '사가정골목시장' '사당시장' '사러가시장' '삼구시장' '삼선골목시장'
 '삼성동 시장(신림6동)' '삼익패션타운' '상계시장' '상계중앙시장' '새마을시장' '새석관시장' '서교시장' '서울약령시장'
 '서울중앙시장' '서원동상점가' '서중시장' '석관시장' '석관황금시장' '석촌시장' '성내골목시장' '성대시장'
 '성동용답상가시장' '세운상가가동' '소공지하도상가' '솔샘시장(미아67동골목시장)' '송화골목시장' '수유북부시장' '수유시장'
 '수유재래시장' '수유전통시장(구)수유골목시장' '수유중앙골목시장' '수유중앙시장' '수유프라자' '수일시장' '숭례문상가'
 '숭인시장' '시청광장 지하쇼핑센터' '신곡종합시장' '신길시장' '신노량진시장' '신도봉시장' '신동시장' '신림종합시장'
 '신림중앙시장' '신림현대상가' '신사상가' '신설종합시장' '신성시장' '신수시장' '신신림시장' '신아타운' '신영사러가시장'
 '신영시장' '신원시장(신림1동)' '신월3동 골목시장' '신월6동 골목시장' '신월7동 골목시장' '신월중앙시장' '신응암시장'
 '신정1동 골목시장' '신정2동 골목시장' '신정3동 골목시장' '신정제일시장' '신중부시장' '신평화패션타운' '신흥시장'
 '쌍문역골목시장' '쑥고개 시장(봉천8동)' '아리랑시장' '아현골목시장' '암사종합시장' '약수시장' '양남시장' '양재시장'
 '양지골목시장' '양지시장' '양지종합시장' '양평시장' '에리어식스' '역삼종합시장' '역촌중앙시장' '연서시장' '연신내상점가'
 '연희사러가' '염리시장' '영도시장' '영동교골목시장' '영동전통시장' '영등포기계상가' '영등포로타리지하도상점가'
 '영등포시장기계공구상가' '영등포시장지하도상점가' '영등포역지하도상점가' '영등포유통상가' '영등포전통시장' '영신상가'
 '영일시장' '영진시장' '영진시장A동' '영진시장B동' '영천시장' '오류시장' '용강동 상점가' '용두시장' '용문시장'
 '우리시장' '우림골목시장' '우림시장' '우성상가' '우이골목시장' '우이시장' '원당종합시장' '월정로시장' '유영시장'
 '유진상가' '을지입구지하상가' '을지지하보도상가' '응암시장' '이경시장' '이문제일시장' '이촌종합시장' '이태원시장'
 '인왕시장' '인헌시장(봉천11동)' '인현시장' '자양골목시장' '자양종합시장' '자유상가' '장미원골목시장'
 '장신구 특화거리 상점가' '장위골목시장' '장위시장' '전곡시장' '전농로터리시장' '정릉시장' '제기시장' '제일상가'
 '제일시장' '제일평화시장' '조광시장' '조양시장' '조원동 펭귄시장(신림8동)' '종각지하쇼핑센터' '종로4가지하상가'
 '종로5가지하상가' '종로신진시장' '중곡제일골목시장' '중곡제일시장' '중랑교종합상가' '중부시장' '중앙노점' '증산종합시장'
 '창동골목시장' '창동신창시장' '창신골목시장' '천호시장' '천호신시장' '청계5가 지하쇼핑센터' '청계6가 지하도상가'
 '청담삼익시장' '청담제일시장' '청량리수산시장' '청량리전통시장' '청량리종합시장' '청량리청과물시장' '청평화시장' '충신시장'
 '태능시장' '통인시장' '통일상가' '평화시장' '포방터시장' '푸른터시장' '풍납시장' '한남프라자' '한아름시장' '한양시장'
 '한일상가' '한일지하상가(마전교지하쇼핑센터)' '합정시장' '행당시장' '현대시장' '홍대 걷고싶은 거리' '화곡본동시장'
 '화곡중앙골목시장' '화곡중앙시장' '화양제일골목시장' '회기시장' '회현지하도상가' '후암시장']

In [388]:
# 가격 테이블과 주소 테이블의 겹치는 시장이름 확인
price_market_name = list(df_price['시장이름'].unique())
address_market_name = list(df_address['시장이름'].unique())

market_name = []
for i in range(len(price_market_name)):
    for j in range(len(address_market_name)):
        if price_market_name[i] == address_market_name[j] :
            market_name.append(price_market_name[i])
print(len(market_name), market_name)

44 ['통인시장', '방학동도깨비시장', '장위골목시장', '마포농수산물시장', '동원시장', '광장시장', '금남시장', '뚝도시장', '후암시장', '청량리종합시장', '남문시장', '신영시장', '고척근린시장', '용문시장', '대림시장', '영등포전통시장', '망원시장', '영천시장', '인왕시장', '신원시장(신림1동)', '자양골목시장', '수유재래시장', '경동시장', '우림시장', '대림중앙시장', '목3동시장', '공릉동 도깨비시장', '돈암제일시장', '원당종합시장', '남대문시장', '청담삼익시장', '현대시장', '둔촌역전통시장', '서울중앙시장', '노룬산골목시장', '화곡본동시장', '방이시장', '대조시장', '마천중앙시장', '관악신사시장(신림4동)', '암사종합시장', '상계중앙시장', '숭인시장', '구로시장']

In [391]:
# 가격테이블에는 있지만 주소테이블에는 없는 시장이름

for i in range(len(df_price['시장이름'].unique())) :    
    if list(df_price['시장이름'].unique())[i] not in market_name :
        print(list(df_price['시장이름'].unique())[i])

방배종합시장
신창시장
남성시장
남구로시장
송화시장
도곡시장
방림시장
공릉동도깨비시장
영동시장

#### 가격테이블 - 주소테이블 시장이름 차이 조정

- 방배종합시장 -> 남부종합시장  
- 신창시장 -> 창동신창시장  
- 남성시장 -> 사당시장  
- 송화시장 -> 송화골목시장  
- 영동시장 -> 영동전통시장  



- 남구로시장 <- 남구로시장(구 구로자율시장)
- 공릉동도깨비시장 <-공릉동 도깨비시장 

도곡시장 -> 주소테이블에 누락  
방림시장 -> 20년도부터 빠져있음. 시장폐쇄가능성 높음

In [461]:
# 가격테이블에서 시장이름 주소테이블과 동일하게 변경

def change_name1(x):
    if x=='방배종합시장':
        return "남부종합시장"
    if x=='신창시장':
        return "창동신창시장"
    if x=='남성시장':
        return "사당시장"
    if x=='송화시장':
        return "송화골목시장"
    if x=='영동시장':
        return "영동전통시장"
    if x=='공릉동 도깨비시장':
        return "공릉동도깨비시장"
    else: return x
    
df_price['시장이름'] = df_price['시장이름'].apply(change_name1)

In [455]:
def change_name2(x):
    if x=='공릉동 도깨비시장':
        return "공릉동도깨비시장"
    if x=='남구로시장(구 구로자율시장)':
        return "남구로시장"
    else: return x
df_address = df_address.copy()    
df_address['시장이름'] = df_address['시장이름'].apply(change_name2)

In [456]:
# 도곡시장, 방림시장 row 삭제

is_true = df_price[df_price['시장이름']=='도곡시장'].index
df_price.drop(is_true, inplace=True)
is_true = df_price[df_price['시장이름']=='방림시장'].index
df_price.drop(is_true, inplace=True)

In [462]:
#가격테이블과 주소테이블 merge
df_price_address = pd.merge(df_price, df_address, on='시장이름', how='left')
df_price_address

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도
0,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708
1,2020,4,2020-12,남부종합시장,호박,1개268g,1500,서초구,37.49492,126.98487
2,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708
3,2020,4,2020-12,통인시장,상추(100g),400g,3000,종로구,37.580818,126.968708
4,2020,4,2020-12,통인시장,호박(인큐베이터),1개,1000,종로구,37.580818,126.968708
...,...,...,...,...,...,...,...,...,...,...
168008,2013,1,2013-01,방이시장,달걀(특란),10개,2150,송파구,37.510362,127.117523
168009,2013,1,2013-01,방이시장,"조기(냉동,국산)",1마리(20cm),1780,송파구,37.510362,127.117523
168010,2013,1,2013-01,방이시장,"명태(러시아,냉동)",1마리(45cm),5000,송파구,37.510362,127.117523
168011,2013,1,2013-01,방이시장,"오징어(냉동,국산)",1마리(25cm),3000,송파구,37.510362,127.117523
168012,2013,1,2013-01,방이시장,"고등어(생물,국산)",1마리(30cm),5000,송파구,37.510362,127.117523

In [463]:
# null 확인
df_price_address.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168013 entries, 0 to 168012
Data columns (total 10 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   년도      168013 non-null  int64
 1   분기      168013 non-null  int64
 2   년도-월    168013 non-null  object
 3   시장이름    168013 non-null  object
 4   품목이름    168009 non-null  object
 5   실판매규격   168013 non-null  object
 6   가격(원)   168013 non-null  int64
 7   자치구명    168013 non-null  object
 8   위도      168013 non-null  object
 9   경도      168013 non-null  object
dtypes: int64(3), object(7)
memory usage: 14.1+ MB

In [465]:
df_price_address[df_price_address['위도'].isnull()]

Empty DataFrame
Columns: [년도, 분기, 년도-월, 시장이름, 품목이름, 실판매규격, 가격(원), 자치구명, 위도, 경도]
Index: []

### 가격-주소 테이블에 유동인구 테이블 병합

In [468]:
# 가격-주소 테이블에 있는 전통시장 수 확인
print(len(df_price_address['시장이름'].unique()), df_price_address['시장이름'].unique())

50 ['통인시장' '남부종합시장' '방학동도깨비시장' '장위골목시장' '창동신창시장' '마포농수산물시장' '동원시장' '광장시장'
 '사당시장' '금남시장' '뚝도시장' '후암시장' '청량리종합시장' '남문시장' '남구로시장' '신영시장' '고척근린시장'
 '용문시장' '대림시장' '영등포전통시장' '망원시장' '영천시장' '인왕시장' '신원시장(신림1동)' '자양골목시장'
 '수유재래시장' '경동시장' '우림시장' '송화골목시장' '대림중앙시장' '목3동시장' '공릉동도깨비시장' '돈암제일시장'
 '원당종합시장' '남대문시장' '청담삼익시장' '현대시장' '둔촌역전통시장' '서울중앙시장' '노룬산골목시장' '화곡본동시장'
 '방이시장' '대조시장' '마천중앙시장' '관악신사시장(신림4동)' '암사종합시장' '상계중앙시장' '숭인시장' '구로시장'
 '영동전통시장']

In [467]:
# 유동인구 테이블에 있는 전통시장 수 확인
print(len(df_customer['시장이름'].unique()), df_customer['시장이름'].unique())

226 ['길동복조리시장' '둔촌역전통시장' '성내골목시장' '천호시장' '동서울시장' '고분다리골목시장' '양지골목시장' '암사종합시장'
 '고덕전통시장' '명일골목시장' '새마을시장' '석촌시장' '방이시장' '마천시장' '풍납시장' '강남개포시장' '도곡시장'
 '청담삼익시장' '논현종합시장' '영동전통시장' '강남시장_강남' '양재시장' '남부종합시장' '우림시장' '미성동도깨비시장'
 '신신림시장' '삼성동시장' '신림중앙시장' '강남골목시장' '신림종합시장' '관악신사시장' '신원시장' '인헌시장'
 '봉천중앙시장' '봉천현대시장' '봉일시장' '봉천제일종합시장' '낙성대시장' '중부시장' '사당시장' '남성역골목시장'
 '남성사계시장' '흑석시장' '상도4동도깨비골목시장' '성대시장' '영도시장' '상도전통시장' '강남시장_동작' '신노량진시장'
 '본동인정시장' '노량진중앙시장' '대림중앙시장' '우리시장' '영진시장A동' '사러가시장' '대신시장' '양남시장' '영일시장'
 '도림시장' '영등포청과시장' '영등포전통시장' '은행나무시장' '박미시장' '현대시장' '대명시장' '푸른터시장' '남문시장'
 '독산동 우시장' '오류시장' '개봉중앙시장' '고척근린시장' '가리봉시장' '남구로시장' '구로시장' '공항시장' '방신전통시장'
 '송화골목시장' '까치산시장' '화곡본동시장' '남부골목시장' '대원종합시장' '화곡중앙골목시장' '신월중앙시장' '등마루시장'
 '신정3동골목시장' '신정2동골목시장' '신정제일시장' '신월7동골목시장' '신월6동골목시장' '신곡종합시장' '신월3동골목시장'
 '경창시장' '월정로시장' '신영시장' '목4동시장' '목3동시장' '목2동시장' '마포농수산물시장' '동진시장' '망원월드컵시장'
 '망원시장' '합정시장' '영진시장' '서교시장' '신수시장' '아현시장' '마포시장' '공덕시장' '백련시장' '모래내시장'
 '포방터시장' '인왕시장' '아현가구거리상점가' '영천시장' '수일시장' '증산종합시장' '대림골목시장' '신응암시장' '녹번시장'
 '대조시장' '역촌중앙시장' '갈현시장' '연서시장' '상계중앙시장' '상계시장' '공릉동도깨비시장' '방학동도깨비시장'
 '쌍문역골목시장' '백운시장' '신도봉시장' '창동골목시장' '창동신창시장' '수유북부시장' '장미원골목시장' '수유중앙시장'
 '강북종합시장' '우이시장' '수유전통시장' '번동북부골목시장' '솔샘시장' '숭인시장' '방천골목시장' '동북시장'
 '석관황금시장' '석관시장' '새석관시장' '번동시장' '장위전통시장' '밤나무골시장' '길음시장' '정릉시장' '정릉아리랑시장'
 '돈암제일시장' '유영시장' '우림골목시장' '묵1동도깨비시장' '태능시장' '중화제일시장' '사가정시장' '면목골목시장'
 '동원시장' '동부골목시장' '이문제일시장' '이경시장' '회기시장' '청량리청과물시장' '전곡시장' '답십리시장' '동부시장'
 '답십리현대시장' '전농로터리시장' '청량리종합시장' '청량리전통시장' '청량리농수산물시장' '서울약령시장' '동서시장'
 '경동시장' '청량리수산시장' '용두시장' '동부청과시장' '구의시장' '조양시장' '영동교골목시장' '능동로골목시장'
 '노룬산골목시장' '자양종합시장' '자양골목시장' '신성골목시장' '면곡골목시장' '중곡제일시장' '화양제일골목시장' '한아름시장'
 '성동용답상가시장' '뚝도시장' '금남시장' '행당시장' '마장축산물시장' '보광시장' '이태원제일시장' '이태원시장'
 '이촌종합시장' '용문전통시장' '만리시장' '신흥시장' '후암시장' '합동(새벽)시장' '서울중앙시장' '백학시장' '약수시장'
 '청평화시장' '제일평화시장' '동평화시장' '방산종합시장' '평화시장' '인현시장' '신중부시장' '남대문시장' '신설종합시장'
 '동묘시장' '창신골목시장' '동문시장' '충신시장' '종로신진시장' '동대문종합시장' '광장시장' '통인시장']

In [469]:
# 가격-주소 테이블과 유동인구 테이블의 겹치는 시장이름 확인
price_address_market_name = list(df_price_address['시장이름'].unique())
customer_market_name = list(df_customer['시장이름'].unique())

market_name = []
for i in range(len(price_address_market_name)):
    for j in range(len(customer_market_name)):
        if price_address_market_name[i] == customer_market_name[j] :
            market_name.append(price_address_market_name[i])
print(len(market_name), market_name)

42 ['통인시장', '남부종합시장', '방학동도깨비시장', '창동신창시장', '마포농수산물시장', '동원시장', '광장시장', '사당시장', '금남시장', '뚝도시장', '후암시장', '청량리종합시장', '남문시장', '남구로시장', '신영시장', '고척근린시장', '영등포전통시장', '망원시장', '영천시장', '인왕시장', '자양골목시장', '경동시장', '우림시장', '송화골목시장', '대림중앙시장', '목3동시장', '공릉동도깨비시장', '돈암제일시장', '남대문시장', '청담삼익시장', '현대시장', '둔촌역전통시장', '서울중앙시장', '노룬산골목시장', '화곡본동시장', '방이시장', '대조시장', '암사종합시장', '상계중앙시장', '숭인시장', '구로시장', '영동전통시장']

In [470]:
# 가격-주소 테이블에는 있지만 유동인구 테이블에는 없는 시장이름

for i in range(len(df_price_address['시장이름'].unique())) :    
    if list(df_price_address['시장이름'].unique())[i] not in market_name :
        print(list(df_price_address['시장이름'].unique())[i])

장위골목시장
용문시장
대림시장
신원시장(신림1동)
수유재래시장
원당종합시장
마천중앙시장
관악신사시장(신림4동)

#### 가격-주소테이블 - 유동인구테이블 시장이름 차이 조정

- 장위골목시장 -> 장위전통시장  
- 용문시장 -> 용문전통시장  
- 신원시장(신림1동) -> 신원시장  
- 수유재래시장 -> 수유전통시장  
- 원당종합시장 -> 인헌시장  
- 마천중앙시장 -> 마천시장  
- 관악신사시장(신림4동) -> 관악신사시장  



- 대림시장 <- 대림골목시장

In [471]:
# 가격-주소테이블에서 시장이름 유동인구테이블과 동일하게 변경

def change_name3(x):
    if x=='장위골목시장':
        return "장위전통시장"
    if x=='용문시장':
        return "용문전통시장"
    if x=='신원시장(신림1동)':
        return "신원시장"
    if x=='수유재래시장':
        return "수유전통시장"
    if x=='원당종합시장':
        return "인헌시장"
    if x=='마천중앙시장':
        return "마천시장"
    if x=='관악신사시장(신림4동)':
        return "관악신사시장"
    else: return x
    
df_price_address['시장이름'] = df_price_address['시장이름'].apply(change_name3)

In [472]:
# 유동인구테이블에서 시장이름 가격-주소테이블테이블과 동일하게 변경

def change_name4(x):
    if x=='대림골목시장':
        return "대림시장"
    else: return x
    
df_customer['시장이름'] = df_customer['시장이름'].apply(change_name4)

In [477]:
#가격-주소 테이블과 유동인구 테이블 merge
df = pd.merge(df_price_address, df_customer, on=['년도','분기','시장이름'], how='left')
df

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
1,2020,4,2020-12,남부종합시장,호박,1개268g,1500,서초구,37.49492,126.98487,...,174.0,176.0,240.0,182.0,358.0,303.0,180.0,175.0,247.0,188.0
2,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
3,2020,4,2020-12,통인시장,상추(100g),400g,3000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
4,2020,4,2020-12,통인시장,호박(인큐베이터),1개,1000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168008,2013,1,2013-01,방이시장,달걀(특란),10개,2150,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168009,2013,1,2013-01,방이시장,"조기(냉동,국산)",1마리(20cm),1780,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168010,2013,1,2013-01,방이시장,"명태(러시아,냉동)",1마리(45cm),5000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168011,2013,1,2013-01,방이시장,"오징어(냉동,국산)",1마리(25cm),3000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168012,2013,1,2013-01,방이시장,"고등어(생물,국산)",1마리(30cm),5000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [478]:
# info 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168013 entries, 0 to 168012
Columns: 536 entries, 년도 to 여성연령대_60_이상_일요일시간대_6_생활인구_수
dtypes: float64(526), int64(3), object(7)
memory usage: 688.3+ MB

In [479]:
# null 확인
# merge를 잘못한게 아니라 특정 년도(2013년), 분기에 유동인구 데이터가 없는 행들임
df[df['총_생활인구_수'].isnull()]

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
138434,2016,1,2016-03,대조시장,사과,1개,1666,은평구,37.609065,126.926346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138435,2016,1,2016-03,대조시장,배(신고),1개,2500,은평구,37.609065,126.926346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138436,2016,1,2016-03,대조시장,배추,1포기,2500,은평구,37.609065,126.926346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138437,2016,1,2016-03,대조시장,무(1kg),1개,1000,은평구,37.609065,126.926346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138438,2016,1,2016-03,대조시장,양파,1망(1.5kg),4000,은평구,37.609065,126.926346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168008,2013,1,2013-01,방이시장,달걀(특란),10개,2150,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168009,2013,1,2013-01,방이시장,"조기(냉동,국산)",1마리(20cm),1780,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168010,2013,1,2013-01,방이시장,"명태(러시아,냉동)",1마리(45cm),5000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168011,2013,1,2013-01,방이시장,"오징어(냉동,국산)",1마리(25cm),3000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168012,2013,1,2013-01,방이시장,"고등어(생물,국산)",1마리(30cm),5000,송파구,37.510362,127.117523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [490]:
# 결측값이 있는 행 전체 제거
df = df[df['총_생활인구_수'].notna()]

In [491]:
df[df['총_생활인구_수'].isnull()]

Empty DataFrame
Columns: [년도, 분기, 년도-월, 시장이름, 품목이름, 실판매규격, 가격(원), 자치구명, 위도, 경도, 총_생활인구_수, 남성_생활인구_수, 여성_생활인구_수, 연령대_10_생활인구_수, 연령대_20_생활인구_수, 연령대_30_생활인구_수, 연령대_40_생활인구_수, 연령대_50_생활인구_수, 연령대_60_이상_생활인구_수, 시간대_1_생활인구_수, 시간대_2_생활인구_수, 시간대_3_생활인구_수, 시간대_4_생활인구_수, 시간대_5_생활인구_수, 시간대_6_생활인구_수, 월요일_생활인구_수, 화요일_생활인구_수, 수요일_생활인구_수, 목요일_생활인구_수, 금요일_생활인구_수, 토요일_생활인구_수, 일요일_생활인구_수, 남성연령대_10_월요일시간대_1_생활인구_수, 남성연령대_10_월요일시간대_2_생활인구_수, 남성연령대_10_월요일시간대_3_생활인구_수, 남성연령대_10_월요일시간대_4_생활인구_수, 남성연령대_10_월요일시간대_5_생활인구_수, 남성연령대_10_월요일시간대_6_생활인구_수, 남성연령대_10_화요일시간대_1_생활인구_수, 남성연령대_10_화요일시간대_2_생활인구_수, 남성연령대_10_화요일시간대_3_생활인구_수, 남성연령대_10_화요일시간대_4_생활인구_수, 남성연령대_10_화요일시간대_5_생활인구_수, 남성연령대_10_화요일시간대_6_생활인구_수, 남성연령대_10_수요일시간대_1_생활인구_수, 남성연령대_10_수요일시간대_2_생활인구_수, 남성연령대_10_수요일시간대_3_생활인구_수, 남성연령대_10_수요일시간대_4_생활인구_수, 남성연령대_10_수요일시간대_5_생활인구_수, 남성연령대_10_수요일시간대_6_생활인구_수, 남성연령대_10_목요일시간대_1_생활인구_수, 남성연령대_10_목요일시간대_2_생활인구_수, 남성연령대_10_목요일시간대_3_생활인구_수, 남성연령대_10_목요일시간대_4_생활인구_수, 남성연령대_10_목요일시간대_5_생활인구_수, 남성연령대_10_목요일시간대_6_생활인구_수, 남성연령대_10_금요일시간대_1_생활인구_수, 남성연령대_10_금요일시간대_2_생활인구_수, 남성연령대_10_금요일시간대_3_생활인구_수, 남성연령대_10_금요일시간대_4_생활인구_수, 남성연령대_10_금요일시간대_5_생활인구_수, 남성연령대_10_금요일시간대_6_생활인구_수, 남성연령대_10_토요일시간대_1_생활인구_수, 남성연령대_10_토요일시간대_2_생활인구_수, 남성연령대_10_토요일시간대_3_생활인구_수, 남성연령대_10_토요일시간대_4_생활인구_수, 남성연령대_10_토요일시간대_5_생활인구_수, 남성연령대_10_토요일시간대_6_생활인구_수, 남성연령대_10_일요일시간대_1_생활인구_수, 남성연령대_10_일요일시간대_2_생활인구_수, 남성연령대_10_일요일시간대_3_생활인구_수, 남성연령대_10_일요일시간대_4_생활인구_수, 남성연령대_10_일요일시간대_5_생활인구_수, 남성연령대_10_일요일시간대_6_생활인구_수, 남성연령대_20_월요일시간대_1_생활인구_수, 남성연령대_20_월요일시간대_2_생활인구_수, 남성연령대_20_월요일시간대_3_생활인구_수, 남성연령대_20_월요일시간대_4_생활인구_수, 남성연령대_20_월요일시간대_5_생활인구_수, 남성연령대_20_월요일시간대_6_생활인구_수, 남성연령대_20_화요일시간대_1_생활인구_수, 남성연령대_20_화요일시간대_2_생활인구_수, 남성연령대_20_화요일시간대_3_생활인구_수, 남성연령대_20_화요일시간대_4_생활인구_수, 남성연령대_20_화요일시간대_5_생활인구_수, 남성연령대_20_화요일시간대_6_생활인구_수, 남성연령대_20_수요일시간대_1_생활인구_수, 남성연령대_20_수요일시간대_2_생활인구_수, 남성연령대_20_수요일시간대_3_생활인구_수, 남성연령대_20_수요일시간대_4_생활인구_수, 남성연령대_20_수요일시간대_5_생활인구_수, 남성연령대_20_수요일시간대_6_생활인구_수, 남성연령대_20_목요일시간대_1_생활인구_수, 남성연령대_20_목요일시간대_2_생활인구_수, 남성연령대_20_목요일시간대_3_생활인구_수, 남성연령대_20_목요일시간대_4_생활인구_수, 남성연령대_20_목요일시간대_5_생활인구_수, 남성연령대_20_목요일시간대_6_생활인구_수, 남성연령대_20_금요일시간대_1_생활인구_수, 남성연령대_20_금요일시간대_2_생활인구_수, ...]
Index: []

[0 rows x 536 columns]

In [492]:
df

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
1,2020,4,2020-12,남부종합시장,호박,1개268g,1500,서초구,37.49492,126.98487,...,174.0,176.0,240.0,182.0,358.0,303.0,180.0,175.0,247.0,188.0
2,2020,4,2020-12,통인시장,양파(1.5kg망),1kg,2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
3,2020,4,2020-12,통인시장,상추(100g),400g,3000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
4,2020,4,2020-12,통인시장,호박(인큐베이터),1개,1000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158837,2014,1,2014-01,방이시장,달걀(특란),10개,2900,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0
158838,2014,1,2014-01,방이시장,"조기(냉동,국산)",1마리(20cm),2000,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0
158839,2014,1,2014-01,방이시장,"명태(러시아,냉동)",1마리(35cm),2400,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0
158840,2014,1,2014-01,방이시장,"오징어(냉동,국산)",1마리(25cm),1980,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0
158841,2014,1,2014-01,방이시장,"고등어(생물,국산)",1마리(30cm),4980,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0

## 가장 빈도수가 많은 품목 선택

In [493]:
#테이블에 있는 품목 수 확인
print(len(df['품목이름'].unique()), df['품목이름'].unique())

89 ['양파(1.5kg망)' '호박' '상추(100g)' '호박(인큐베이터)' '쇠고기(한우,불고기)' '돼지고기(생삼겹살)'
 '닭고기(육계)' '달걀(10개)' '달걀(30개)' '조기(냉동,수입산)' '명태(러시아,냉동)' '오징어(생물,국산)'
 '고등어(생물,국산)' '무(세척무, 중)' '오이' '사과(부사, 300g)' '배추(중간)' '배(신고, 600g)' '오징어'
 '명태' '배추' '무' '닭고기' '돼지고기' '쇠고기' '양파' '조기' '사과' '배' '고등어' '상추'
 '배추(2.5~3kg)' '조기(국산,생물)' '동태' '오이(다다기)' '애호박' '무(1kg)' '명태(생물,수입산)'
 '쇠고기(한우1등급)' '명태(냉동,수입산)' '조기(생물,국산)' '명태(45cm,수입산)' '조기(국산,냉동)'
 '돼지고기(삼겹살)' '닭고기(중간)' '닭고기(토종닭)' '배추(국산)' '배(신고)' '양파(작은망)' '오징어(냉동,국산)'
 '무(세척무)' '배(중품)' '호박(인큐베이터),중간' '쇠고기(육우,불고기)' '조기(냉동,국산)' '배(신고),중급(대)'
 '사과(부사)' '냉동참조기(20cm,국산)' '고등어(냉동,국산)' '달걀' '사과(부사),중급(대)' '명태(생물,국산)'
 '달걀(왕란)' '오징어(냉동,수입산)' nan '고등어(생물,수입산)' '조기(생물,수입산)' '사과(중품)'
 '조기(중국산,생물)' '고등어(30cm,국산)' '오징어(생물,수입산)' '고등어(냉동,수입산)' '오징어(냉동)'
 '배(중품),신고' '고등어(30cm,수입산)' '사과(부사),중급(중)' '쇠고기(한우2등급)' '사과(중품), 부사'
 '명태(일본산,냉동)' '갈치(생물, 국산)' '쇠고기(육우1등급)' '배(신고),중급(중)' '냉동참조기(20cm,수입)'
 '달걀(특란)' '명태(냉동,국산)' '삼겹살' '달걀(중란)' '갈치(냉동,국산)' '오이(중간)']

In [507]:
# 품목의 빈도수 계산
freq = df[['시장이름','품목이름']].groupby(['품목이름']).count()
freq.sort_values(by = ['시장이름'], ascending = False)

              시장이름
품목이름
오이(다다기)       7592
달걀(10개)       7354
달걀(30개)       7350
쇠고기(한우,불고기)   7280
배추(2.5~3kg)   7053
...            ...
명태(일본산,냉동)       3
쇠고기(육우1등급)       2
사과(부사),중급(중)     2
갈치(생물, 국산)       1
갈치(냉동,국산)        1

[88 rows x 1 columns]

### 빈도수 1위 '오이(다다기)' dataframe

In [528]:
# 품목이름이 오이(다다기)인 row만 가져오기
is_true = df['품목이름']=='오이(다다기)'
df_cucumber = df[is_true]

In [532]:
# 인덱스 reset
df_cucumber = df_cucumber.reset_index().drop(['index'], axis=1)
df_cucumber

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,2020-12,장위전통시장,오이(다다기),"1개 (2개 1,500원)",750,성북구,37.612047,127.050667,...,1049.0,1072.0,1413.0,1009.0,2101.0,1773.0,1059.0,1048.0,1397.0,1013.0
1,2020,4,2020-12,장위전통시장,오이(다다기),"1개 (2개 1,500원)",750,성북구,37.612047,127.050667,...,1049.0,1072.0,1413.0,1009.0,2101.0,1773.0,1059.0,1048.0,1397.0,1013.0
2,2020,4,2020-12,장위전통시장,오이(다다기),"1개 (1봉 2개 1,000원)",500,성북구,37.612047,127.050667,...,1049.0,1072.0,1413.0,1009.0,2101.0,1773.0,1059.0,1048.0,1397.0,1013.0
3,2020,4,2020-12,장위전통시장,오이(다다기),1개,500,성북구,37.612047,127.050667,...,1049.0,1072.0,1413.0,1009.0,2101.0,1773.0,1059.0,1048.0,1397.0,1013.0
4,2020,4,2020-12,장위전통시장,오이(다다기),"1개 (2개 팩 1,500원)",750,성북구,37.612047,127.050667,...,1049.0,1072.0,1413.0,1009.0,2101.0,1773.0,1059.0,1048.0,1397.0,1013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7587,2014,1,2014-01,수유전통시장,오이(다다기),1개,666,강북구,37.633569,127.021718,...,491.0,445.0,466.0,84.0,0.0,112.0,287.0,317.0,340.0,37.0
7588,2014,1,2014-01,노룬산골목시장,오이(다다기),1개,900,광진구,37.536607,127.064587,...,15.0,12.0,14.0,2.0,0.0,1.0,2.0,1.0,6.0,0.0
7589,2014,1,2014-01,자양골목시장,오이(다다기),1개,1000,광진구,37.53378,127.081558,...,232.0,188.0,214.0,42.0,0.0,59.0,119.0,124.0,157.0,26.0
7590,2014,1,2014-01,마천시장,오이(다다기),1개,500,송파구,37.497384,127.15001,...,249.0,231.0,250.0,25.0,0.0,42.0,128.0,155.0,165.0,10.0
7591,2014,1,2014-01,방이시장,오이(다다기),1개,800,송파구,37.510362,127.117523,...,365.0,317.0,322.0,47.0,0.0,92.0,190.0,189.0,204.0,34.0

In [540]:
p = re.compile('^1개')

for i in range(len(df_cucumber['실판매규격'])):
    m = p.findall(df_cucumber['실판매규격'][i])
    if m == [] :
        print(df_cucumber['실판매규격'][i],'가격 : ',df_cucumber['가격(원)'][i])

3개(680g) 가격 :  2500
3개(714g) 가격 :  2500
3개(684g) 가격 :  2500
2개(425g) 가격 :  1500
3개(764g) 가격 :  2500
1망 3개 가격 :  1650
1팩 3개 가격 :  2000
1팩 2개 가격 :  1800
1팩 2개 가격 :  1800
1팩 2개 가격 :  1800
1팩 2개 가격 :  1400
230g 가격 :  670
1 개 가격 :  700
1팩(450g) 가격 :  2680
1팩(480g) 가격 :  2680
1팩(420g) 가격 :  1980
1팩(420g) 가격 :  1980
1팩(450g) 가격 :  2680
1팩(420g) 가격 :  1980
1팩(420g) 가격 :  1980
3개(764g) 가격 :  2500
3개(645g) 가격 :  2500
3개(743g) 가격 :  2500
240g 가격 :  700
3개(721g) 가격 :  2500
3개(615g) 가격 :  2500
3개(670g) 가격 :  2500
230g 가격 :  700
1 개 가격 :  800
1 개 가격 :  900
1봉(3개) 가격 :  2500
1 개 가격 :  700
230g 가격 :  500
230g 가격 :  500
230g 가격 :  670
1 개 가격 :  700
1 개 가격 :  700
240g 가격 :  830
2개(369g) 가격 :  1000
3개(492g) 가격 :  1500
3개(628g) 가격 :  1500
230g 가격 :  670
230g 가격 :  400
1팩(3개) 가격 :  2500
2개(402g) 가격 :  1000
230g 가격 :  400
230g 가격 :  700
2개(303g) 가격 :  1000
3개(594g) 가격 :  2000
3개(486g) 가격 :  1500
240g 가격 :  500
220g 가격 :  400
230g 가격 :  400
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  700
3개(487g) 가격 :  1500
3개(618g) 가격 :  1300
2개(432g) 가격 :  1000
2개(438g) 가격 :  1500
3개(450g) 가격 :  1500
4개(828g) 가격 :  2000
2개(365g) 가격 :  1000
2개(463g) 가격 :  1000
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
240g 가격 :  670
1망 3개 가격 :  1400
1망 3개 가격 :  1400
1팩 3개 가격 :  1500
1팩 3개 가격 :  1500
220g 가격 :  400
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1팩(420g) 가격 :  1980
1팩(430g) 가격 :  2500
1팩(410g) 가격 :  1380
1팩(410g) 가격 :  1380
1팩(460g) 가격 :  1280
1팩(330g) 가격 :  1380
3개(618g) 가격 :  2000
2개(342g) 가격 :  1000
3개(421g) 가격 :  1500
3개(611g) 가격 :  1000
2개(426g) 가격 :  1000
3개(624g) 가격 :  2000
2개(306g) 가격 :  1000
2개(269g) 가격 :  1500
4개(796g) 가격 :  2000
3개(632g) 가격 :  2000
4개(봉) 가격 :  2000
5개(842g) 가격 :  2000
230g 가격 :  400
3개(413g) 가격 :  2000
2개(278g) 가격 :  1000
3개(626g) 가격 :  2000
1팩(460g) 가격 :  1680
1팩(450g) 가격 :  1080
1팩(410g) 가격 :  1680
1팩(420g) 가격 :  2580
1팩(420g) 가격 :  2580
1팩(410g) 가격 :  1680
1팩(460g) 가격 :  1680
1팩(500g) 가격 :  1080
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
230g 가격 :  500
230g 가격 :  500
230g 가격 :  400
1 개 가격 :  600
1 개 가격 :  500
1 개 가격 :  450
1 개 가격 :  500
1팩 2개  가격 :  2600
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1팩 3개 가격 :  1400
1망 3개 가격 :  1500
1팩 2개 가격 :  1000
1팩 3개 가격 :  1500
1팩 3개팩 가격 :  1400
220g 가격 :  700
220g 가격 :  400
220g 가격 :  400
230g 가격 :  500
1팩 2개 가격 :  2000
1망  가격 :  2000
1팩 2개  가격 :  2400
220g 가격 :  1300
1ro 가격 :  1000
1 개 가격 :  1250
1팩(418g) 가격 :  2580
1 개 가격 :  1300
1 개 가격 :  1300
1팩(418g) 가격 :  2580
1 개 가격 :  1250
210g 가격 :  1300
1ㄱ 가격 :  1100
1ro 가격 :  750
1 개 가격 :  700
1 개 가격 :  1000
1 개 가격 :  1200
1 개 가격 :  1500
1 개 가격 :  1000
1 개 가격 :  700
`1개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  550
1 개 가격 :  900
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  400
1 개 가격 :  550
1 개 가격 :  550
1 개 가격 :  350
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  450
1 개 가격 :  450
1게 가격 :  300
1 개 가격 :  600
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  400
1 개 가격 :  400
1 개 가격 :  1000
1 개 가격 :  1000
1 개 가격 :  830
1 개 가격 :  830
1 개 가격 :  1100
1 개 가격 :  1000
1 개 가격 :  1000
1 개 가격 :  1400
1 개 가격 :  1000
1 개 가격 :  700
1 개 가격 :  750
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  900
1 개 가격 :  700
100g 가격 :  1000
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
 1개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  900
1 개 가격 :  600
1 개 가격 :  800
1 개 가격 :  600
1 개 가격 :  900
1 개 가격 :  600
1 개 가격 :  400
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  750
1 개 가격 :  1200
1 개 가격 :  750
1 개 가격 :  900
1 개 가격 :  700
1 개 가격 :  830
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  1000
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  500
1RO 가격 :  833
1 개 가격 :  600
1 개 가격 :  500
1 개 가격 :  1000
1 개 가격 :  600
1 개 가격 :  500
1 개 가격 :  1000
1 개 가격 :  500
1망 1000 가격 :  1000
1 개 가격 :  1100
1 개 가격 :  1000
1 개 가격 :  600
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  600
1 개 가격 :  1200
1 개 가격 :  1100
1 개 가격 :  1000
1 개 가격 :  500
1 개 가격 :  600
1 개 가격 :  600
1 개 가격 :  800
1 개 가격 :  600
1 개 가격 :  600
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  400
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  350
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  450
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  350
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  400
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  600
1 개 가격 :  400
1 개 가격 :  600
1 개 가격 :  600
1 개 가격 :  700
1 개 가격 :  750
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  800
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  800
1 개 가격 :  1000
1 개 가격 :  500
1 개 가격 :  600
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  700
1 개 가격 :  833
1 개 가격 :  1000
1 개 가격 :  500
1 개 가격 :  500
100g 가격 :  500
1 개 가격 :  700
1 개 가격 :  500
1 개 가격 :  400
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 개 가격 :  500
1 가격 :  700
1 가격 :  700
1 가격 :  600
 1개 가격 :  500
개 가격 :  927
1 개 가격 :  800
1 개 가격 :  670
개 가격 :  1060
개 가격 :  666
개 가격 :  1000
개 가격 :  1060
개 가격 :  827
개 가격 :  660
개 가격 :  963
개 가격 :  727
개 가격 :  1127
개 가격 :  1327
개 가격 :  263
개 가격 :  330
개 가격 :  426
개 가격 :  793

### 빈도수 2위 '달걀(10개)	' dataframe

In [544]:
# 품목이름이 달걀(10개) 인 row만 가져오기
is_true = df['품목이름']=='달걀(10개)'
df_egg_10 = df[is_true]

In [545]:
# 인덱스 reset
df_egg_10 = df_egg_10.reset_index().drop(['index'], axis=1)
df_egg_10

,년도,분기,년도-월,시장이름,품목이름,실판매규격,가격(원),자치구명,위도,경도,...,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2020,4,2020-12,통인시장,달걀(10개),10개(600g),2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
1,2020,4,2020-12,통인시장,달걀(10개),10개(600g),2000,종로구,37.580818,126.968708,...,548.0,588.0,769.0,524.0,932.0,760.0,511.0,532.0,703.0,508.0
2,2020,4,2020-12,방학동도깨비시장,달걀(10개),10개(520g),2000,도봉구,37.66576,127.035292,...,713.0,844.0,1206.0,718.0,940.0,833.0,617.0,771.0,1084.0,669.0
3,2020,4,2020-12,방학동도깨비시장,달걀(10개),10개(520g),2000,도봉구,37.66576,127.035292,...,713.0,844.0,1206.0,718.0,940.0,833.0,617.0,771.0,1084.0,669.0
4,2020,4,2020-12,방학동도깨비시장,달걀(10개),10개(520g),2000,도봉구,37.66576,127.035292,...,713.0,844.0,1206.0,718.0,940.0,833.0,617.0,771.0,1084.0,669.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7349,2017,1,2017-02,목3동시장,달걀(10개),10개,3750,양천구,37.548263,126.866815,...,280.0,153.0,146.0,43.0,6.0,102.0,174.0,107.0,134.0,19.0
7350,2017,1,2017-02,대조시장,달걀(10개),10개,2500,은평구,37.609065,126.926346,...,28.0,31.0,39.0,22.0,37.0,43.0,38.0,31.0,37.0,15.0
7351,2017,1,2017-02,대림시장,달걀(10개),10개,2500,은평구,37.586763,126.91761,...,103.0,101.0,120.0,63.0,53.0,55.0,84.0,99.0,106.0,43.0
7352,2017,1,2017-02,대림시장,달걀(10개),10개,2500,은평구,37.491372,126.907663,...,103.0,101.0,120.0,63.0,53.0,55.0,84.0,99.0,106.0,43.0
7353,2017,1,2017-02,현대시장,달걀(10개),10개,3000,금천구,37.459819,126.904319,...,282.0,286.0,383.0,190.0,201.0,201.0,215.0,259.0,322.0,138.0

In [546]:
p = re.compile('^10개')

for i in range(len(df_egg_10['실판매규격'])):
    m = p.findall(df_egg_10['실판매규격'][i])
    if m == [] :
        print(df_egg_10['실판매규격'][i],'가격 : ',df_egg_10['가격(원)'][i])

특란670g 가격 :  2000
특란600g 가격 :  2000
특란600g 가격 :  2000
특란670g 가격 :  2000
특란600g 가격 :  2000
520g 가격 :  2000
특란670g 가격 :  2000
500g 가격 :  2500
520g 가격 :  2000
560g 가격 :  2000
500g 가격 :  2500
500g 가격 :  2500
특란 가격 :  2400
특란 가격 :  2400
10게 가격 :  2500
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
520g 가격 :  2000
520g 가격 :  2000
500g 가격 :  2000
560g 가격 :  2000
500g 가격 :  2000
490g 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
490g 가격 :  2500
특란670g 가격 :  2000
10걔(500g) 가격 :  4500
560g 가격 :  2000
500g 가격 :  2000
500g 가격 :  2000
520g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
500g 가격 :  2000
500g 가격 :  2000
560g 가격 :  2000
500g 가격 :  2000
520g 가격 :  2000
520g 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
480g 가격 :  2500
500g 가격 :  2500
특란 가격 :  2000
560g 가격 :  2000
500g 가격 :  2500
10(개란) 가격 :  1500
520g 가격 :  2000
560g 가격 :  2000
510g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란690g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란670g 가격 :  2000
특란690g 가격 :  2000
특란670g 가격 :  2000
1마리520g 가격 :  2000
590g 가격 :  2000
특란690g 가격 :  2000
특란670g 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
520g 가격 :  2000
500g 가격 :  2000
450g 가격 :  2000
500g 가격 :  2000
520g 가격 :  2000
510g 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
520g 가격 :  2000
5940g 가격 :  2000
500g 가격 :  2500
490g 가격 :  2500
520g 가격 :  2000
500g 가격 :  2500
520g 가격 :  2000
510g 가격 :  2500
특란600g 가격 :  2000
1마리(350g) 가격 :  3300
1마리(390g) 가격 :  3300
특란700g 가격 :  2000
1마리520g 가격 :  2000
특란 가격 :  2000
510g 가격 :  2500
특란670g 가격 :  2000
특란700g 가격 :  2000
520g 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
520g 가격 :  2000
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
특란 가격 :  1800
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  1800
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
10구 가격 :  2900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10r개 가격 :  3000
특란 가격 :  6000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  6000
10구 가격 :  39000
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
10그 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10 구 가격 :  2900
10구 가격 :  2900
10구 가격 :  2900
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
10구 가격 :  3800
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
10r개 가격 :  3000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  3800
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2400
10 가격 :  3500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
1마리 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2700
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
30개 가격 :  1500
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  200
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3900
10구 가격 :  3900
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2000
10구 가격 :  3980
10구 가격 :  3980
10구 가격 :  3800
10구 가격 :  3900
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  5000
1마리 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3980
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  1500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  1500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
1마리 가격 :  2850
특란 가격 :  2400
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
1마리 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3980
1개 가격 :  4300
특란 가격 :  2000
왕란 가격 :  5000
왕란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
왕란 가격 :  6000
특란 가격 :  2500
특란 가격 :  2500
왕란 가격 :  5000
특란 가격 :  2500
특란 가격 :  2500
특란 가격 :  2000
10구 가격 :  3980
특란 가격 :  2000
특란 가격 :  2000
10구 가격 :  3980
1개 가격 :  3980
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  1800
왕란 가격 :  2000
왕란 가격 :  2500
특란 가격 :  2400
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
10구 가격 :  3980
특란 가격 :  2400
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
10구 가격 :  3980
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
10r개 가격 :  1533
10구 가격 :  3980
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2000
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
 10개 가격 :  2950
10구 가격 :  3980
특란 가격 :  2000
특란 가격 :  2400
특란 가격 :  2000
특란 가격 :  2500
(10개) 가격 :  1600
(10개) 가격 :  1100
특란 가격 :  2000
특란 가격 :  2000
왕란 가격 :  2000
왕란 가격 :  2000
1kg 가격 :  6000
왕란 가격 :  2000
왕란 가격 :  2000
10구 가격 :  3980
특란 가격 :  2400
특란 가격 :  1500
특란 가격 :  3000
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2000
10 가격 :  1830
10 가격 :  1830
10 가격 :  1700
왕란 가격 :  2000
왕란 가격 :  2000
 10개 가격 :  1700
10구 가격 :  3980
특란 가격 :  2000
개 가격 :  4300
특란 가격 :  2500
특란 가격 :  2000
특란 가격 :  2500
특란 가격 :  2000
개 가격 :  4300
특란 가격 :  2500
특란 가격 :  2000
개 가격 :  3950
특란 가격 :  2500
특란 가격 :  2000
개 가격 :  4300
특란 가격 :  2500
특란 가격 :  2000
개 가격 :  4300
개 가격 :  4700
특란 가격 :  2500
특란 가격 :  2000
개 가격 :  4950
개 가격 :  5600
개 가격 :  5600
개 가격 :  5600
개 가격 :  4950
개 가격 :  4950
10알 가격 :  3000
10알 가격 :  3000
10구 가격 :  5800